# Generated by Django 4.0 on 2022-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodels',
            name='city',
            field=models.CharField(choices=[('MU', 'Mumbai'), ('DL', 'Delhi'), ('CH', 'Chennai'), ('BG', 'Banglore'), ('KO', 'Kolkata')], default='MU', max_length=2),
        ),
    ]
