# Generated by Django 4.0 on 2022-01-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_rename_emailmodels_emailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai'), ('Banglore', 'Banglore'), ('Kolkata', 'Kolkata')], default='Mumbai', max_length=100),
        ),
    ]
