# Generated by Django 4.0 on 2022-01-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0004_alter_emailmodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai'), ('Bengaluru', 'Bengaluru'), ('Kolkata', 'Kolkata')], default='Mumbai', max_length=100),
        ),
    ]
